# Generated by Django 3.2.7 on 2021-09-15 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_action',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('Credit_card', models.BooleanField(verbose_name='Счет карты кредитный')),
                ('date', models.DateField(default='2021-09-15', verbose_name='Время')),
                ('Amount', models.IntegerField(verbose_name='Сумма')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('Purpose_of_payment', models.CharField(max_length=100, verbose_name='Назначение платежа')),
                ('MCC_code', models.IntegerField(verbose_name='МСС код')),
                ('MCC_decode', models.CharField(max_length=100, verbose_name='Расшифровка МСС')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='логин')),
            ],
        ),
    ]
